base_url = "https://cosmevalera.github.io"
title = "Cosme Web"

compile_sass = true

[markdown]
highlight_code = false

build_search_index = false

[extra]
greeting = "Hello!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:mail@example.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" }
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"