base_url = "https://cosmevalera.github.io"
title = "Cosme Web"

compile_sass = true

[markdown]
highlight_code = false

build_search_index = false

[extra]
links = [
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" }
]